pub mod board;
pub mod board_config;
mod board_map;
pub mod board_square;
pub mod buff;
pub mod castle_points;
pub mod castle_x_points;
pub mod color;
pub mod colored_property;
pub mod debuff;
pub mod dimension;
pub mod heat_map;
mod ids_generator;
pub mod last_board_changes;
mod move_constraints;
pub mod move_score;
mod moves_map;
pub mod piece;
pub mod piece_id;
pub mod piece_move;
pub mod player;
pub mod point;
pub mod promote_piece;
pub mod square;
pub mod squares_map;
pub mod strategy_point;
pub mod strategy_points;
pub mod utils;
pub mod vector;
pub mod vector_points;
mod x_ray_pieces;

